#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  pull_request:
    branches:
      - v1.4-andium
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  push:
    branches:
      - v1.4-andium
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true


jobs:
  duckdb-latest-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.4-andium
    with:
      duckdb_version: v1.4.3
      extension_name: spatial
      ci_tools_version: v1.4-andium
      vcpkg_commit: ce613c41372b23b1f51333815feb3edd87ef8a8b

  duckdb-latest-deploy:
    name: Deploy extension binaries
    needs: duckdb-latest-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.4-andium
    secrets: inherit
    with:
      duckdb_version: v1.4.3
      ci_tools_version: v1.4-andium
      extension_name: spatial
      deploy_latest: ${{ startsWith(github.ref, 'refs/heads/v') || github.ref == 'refs/heads/main' }}
